project:
  type: website

website:
  title: "Blue-Prints Blog"
  description: "Blue-Prints Information Security Blog"
  site-url: https://www.blue-prints.blog/
  favicon: assets/favicon.ico

  twitter-card: 
    image: "https://www.blue-prints.blog/assets/blog_icons/card.png"
  open-graph: 
    image: "https://www.blue-prints.blog/assets/blog_icons/card.png"

  google-analytics: 
    tracking-id: "G-XGT9C0L1TL"
    anonymize-ip: true

  navbar:
    background: "#2e3f58"
    left:
      - href: index.html
        text: "Home"
      - href: content/blog/blog.html
        text: "Blog"
    right:
      - href: content/blog/blog.xml
        icon: rss
      - href: https://www.blue-prints.blog
        icon: github

format:
  html:
    theme: 
      dark: assets/theme-dark.scss
      light: assets/theme-light.scss
    toc: true
    smooth-scroll: true
    highlight-style: github
 
execute:
  freeze: auto

resources:
  - CNAME
  - assets/blog_icons/card.png




